apiVersion: v2
appVersion: v1.2.1
name: synology-csi-talos
description: A Helm chart for the Synology CSI Driver
keywords:
  - Synology
  - CSI Driver
kubeVersion: ">= 1.20.0"
sources:
  - https://github.com/djcopley/synology-csi-talos/tree/main
  - https://github.com/SynologyOpenSource/synology-csi/tree/main
version: 0.10.0
